Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu12"
    config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box"

    config.vm.synced_folder "../", "/home/vagrant/pyperf"

    config.vm.provider :virtualbox do |vb|

        vb.customize ["modifyvm", :id, "--memory", "512"]

    end

    config.vm.provision "shell", path: "setup.sh"

end
